@startuml
title Users Service Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(UsersService, "Сервис управления данными о пользователях") {
  Container(App, "Application", "Java/Python/Go", "Хранит данные о пользователях, ролях и разрешениях")
  Container(Database, "Database", "PostgreSQL", "данные о пользователях, ролях и разрешениях")
}

Container(App, "Application", "Java, Spring") {
  Component(UsersController, "UsersController", "Обрабатывает запросы на получение данных телеметрии устройств")
  Component(ServiceLayer, "Users Service Layer", "Слой бизнес-логики")
  Component(RepositoryLayer, "Users Repository Layer", "Слой взаимодействия с БД")
}

Rel(UsersController,ServiceLayer,"Вызывает бизнес-логику")
Rel(ServiceLayer,RepositoryLayer,"чтения/записи данных о пользователе, роли и разрешении")
Rel(RepositoryLayer,Database,"чтения/записи данных о пользователе, роли и разрешении")
@enduml