@startuml
autonumber

title [Sequence]: Процесс создания автоматического сценария работы устройства

actor "User" as user
participant client as "web/mobile client"
box "Device Management Service"
    participant DeviceManagementController as "Device Management Controller"
    participant ServiceLayer as "Device Management Service"
endbox
participant DevicesService as "Devices Service"
participant ScenarioService as "Scenario Service"
queue "Kafka" as kafka #ff7f00

user -> client: пользователь создал сценарий для устройства
client -> DeviceManagementController: Создай сценарий для устроства
DeviceManagementController -> DevicesService: запрос данных об устроистве
DevicesService --> DeviceManagementController: return Данные об устройстве
DeviceManagementController -> ServiceLayer: сохранение сценария
ServiceLayer -> ScenarioService: сохранение сценария
ScenarioService --> ServiceLayer: return scenario_id
ServiceLayer -> DevicesService: обновление данных модуля(сохранение сценария)
DevicesService --> ServiceLayer: return Ok
ServiceLayer -> kafka: отправка команд устройству
ServiceLayer --> DeviceManagementController: return Ok
DeviceManagementController --> client: return Ok
client --> user: return Ok

@enduml