@startuml
autonumber

title [Sequence]: Процесс просмотра телеметрии устройства

actor "User" as user
participant client as "web/mobile client"
box "Device Management Service"
    participant DeviceManagementController as "Device Controller"
    participant ServiceLayer as "Device Management Service"
endbox

participant TelemetryService as "Telemetry Management Service"

user -> client: Просмотр телеметрии устройств
client -> DeviceManagementController: запрос данных телеметрии устройства
DeviceManagementController -> ServiceLayer: запрос данных телеметрии устройства
ServiceLayer -> TelemetryService: запрос данных телеметрии устройства
TelemetryService --> ServiceLayer: return данные телеметрии устройства
ServiceLayer --> DeviceManagementController: return данные телеметрии устройства
DeviceManagementController --> client: return данные телеметрии устройства
client --> user: return данные телеметрии устройства

@enduml