@startuml
autonumber

title [Sequence]: Процесс просмотра телеметрии устройства

actor "User" as user
participant client as "web/mobile client"
box "Telemetry Management Service"
    participant TelemetryController as "Telemetry Controller"
    participant ServiceLayer as "Telemetry Service Layer"
    participant RepositoryLayer as "Telemetry Repository Layer"
    database DB as "telemetry_db" #0080ff
endbox

user -> client: Просмотр телеметрии устройств
client -> TelemetryController: запрос данных телеметрии устройства
TelemetryController -> ServiceLayer: запрос данных телеметрии устройства
ServiceLayer -> RepositoryLayer: запрос данных телеметрии устройства
RepositoryLayer -> DB: запрос данных телеметрии устройства
RepositoryLayer <-- DB: return данные телеметрии устройства
ServiceLayer <-- RepositoryLayer: return данные телеметрии устройства
TelemetryController <-- ServiceLayer: return данные телеметрии устройства
TelemetryController --> client: return данные телеметрии устройства
client --> user: return данные телеметрии устройства

@enduml